# Generated by Django 4.2.2 on 2023-06-16 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name Of Event')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('event_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=255, verbose_name='Gender')),
                ('max_seat', models.BigIntegerField(verbose_name='Max Seat')),
                ('date_of_event', models.DateField(verbose_name='Date Of Event')),
                ('time', models.TimeField(verbose_name='Time Of Event')),
                ('duration', models.IntegerField(verbose_name='Duration of Event')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField(verbose_name='Booking time')),
                ('no_of_seats', models.IntegerField(verbose_name='No of seats')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_booking', to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
